name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build  # Change this command based on your build process

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
      run: vercel --token $VERCEL_TOKEN --prod
